apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: flywheel
spec:
  dspVersion: v2
  apiServer:
    enableSamplePipeline: false
  objectStorage:
    externalStorage:
      host: minio.minio.svc:9000
      scheme: http
      bucket: pipelines
      s3CredentialsSecret:
        secretName: hub-credentials
        accessKey: s3-access-key
        secretKey: s3-secret-key
  database:
    mariaDB:
      deploy: true
